/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : SVG2PDF
 #	author : miyako
 #	2013/09/09
 #
 # --------------------------------------------------------------------------------*/

#ifndef MIN
#define	MIN(a,b) (((a)<(b))?(a):(b))
#endif /* MIN */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#include <cairo.h>
#include <cairo-pdf.h>
#include <svg-cairo.h>

#ifdef WIN32
#include "Shlwapi.h"
#include "WinInet.h"
#endif

// --- Convert Many
void SVGL_Convert_array(sLONG_PTR *pResult, PackagePtr pParams);

// --- Convert One
void SVGL_Convert(sLONG_PTR *pResult, PackagePtr pParams);

// --- URL
void URL_Convert_from_path(sLONG_PTR *pResult, PackagePtr pParams);
void URL_Convert_to_path(sLONG_PTR *pResult, PackagePtr pParams);